name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cithub Repository에 올린 파일들을 불러오기
        uses: actions/checkout@v4

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

#      - name: 빌드된 파일 이름 변경하기
#        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar
#
#      - name: 압축하기
#        run: tar -czvf $GITHUB_SHA.tar.gz project.jar appspec.yml scripts

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Docker 이미지 생성
        run: docker build -t mingyu-server .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag mingyu-server ${{ steps.login-ecr.outputs.registry }}/mingyu-server:latest

      - name: ECR에 Docker 이미지 Push
        run: docker push ${{ steps.login-ecr.outputs.registry }}/mingyu-server:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop mingyu-server || true
            docker rm mingyu-server || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/mingyu-server:latest
            docker run -d --name mingyu-server -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/mingyu-server:latest



#      - name: S3에 프로젝트 폴더 업로드하기
#        run: aws s3 cp --region us-east-1 ./$GITHUB_SHA.tar.gz s3://mingyu-server/$GITHUB_SHA.tar.gz
#
#      - name: CodeDeploy를 활용해 EC2에 프로젝트 코드를 배포하라고 명령
#        run: aws deploy create-deployment
#          --application-name mingyu-server
#          --deployment-config-name CodeDeployDefault.AllAtOnce
#          --deployment-group-name Production
#          --s3-location bucket=mingyu-server,bundleType=tgz,key=$GITHUB_SHA.tar.gz



#      - name: SCP로 EC2에 빌드된 파일 전송하기
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          source: project.jar
#          target: /home/ubuntu/mingyu-server/tobe
#
#
#      - name: SSH(원격 접속)로 EC2에 접속하기
#        uses: appleboy/ssh-action@v1.0.3
##        env:
##          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          envs: APPLICATION_PROPERTIES
#          script_stop: true
#          script: |
#            rm -rf /home/ubuntu/mingyu-server/current
#            mkdir /home/ubuntu/mingyu-server/current
#            mv /home/ubuntu/mingyu-server/tobe/project.jar /home/ubuntu/mingyu-server/current/project.jar
#            cd /home/ubuntu/mingyu-server/current
#            sudo fuser -k -n tcp 8080 || true
#            nohup java -jar project.jar > ./output.log 2>&1 &
#            rm -rf /home/ubuntu/mingyu-server/tobe
#
##          script: |
##            cd /home/ubuntu/mingyu-server
##            rm -rf src/main/resources/application.yml
##            git pull origin main
##            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
##            ./gradlew clean build
##            sudo fuser -k -n tcp 8080 || true
##            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &